ABCD-OnlineMall/Models/Product.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace ABCD_OnlineMall.Models
{
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? StoreId { get; set; }
        public int? BrandId { get; set; }
        public string Category { get; set; }
        public string ImageName { get; set; }
        [NotMapped]
        [Display(Name = "Upload File")]
        [Required]
        public IFormFile ImageFile { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Store Store { get; set; }
    }
}

ABCD-OnlineMall/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ABCD_OnlineMall.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace ABCD_OnlineMall.Controllers
{
    public class BrandsController : Controller
    {
        private readonly mallDBContext _context;
        
        private readonly IWebHostEnvironment environment;

        public BrandsController(mallDBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            environment = hostEnvironment;
        }

        // GET: Brands
        public async Task<IActionResult> Index()
        {
            var mallDBContext = _context.Brands.Include(b => b.Store);
            return View(await mallDBContext.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .Include(b => b.Store)
                .FirstOrDefaultAsync(m => m.BrandId == id);
            
               
                
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }
        public async Task<IActionResult> DetailsClient(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = new Sharemodel2();
            model.Brands = await _context.Brands.Include(b => b.Store)
                .FirstOrDefaultAsync(m => m.BrandId == id);
            model.Products = await _context.Products.Where(p => p.BrandId == id).ToListAsync();

            
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }
        // GET: Brands/Create
        public IActionResult Create()
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            ViewData["StoreName"] = new SelectList(_context.Stores, "StoreName", "StoreName");
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId");
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,[Bind("BrandId,BrandName,BrandUrl,ImageName,StoreId,ImageFile")] Brand brand)
        {
            if (ModelState.IsValid)
            {
              string fileName = Path.GetFileName(brand.ImageFile.FileName);
                string file_path = Path.Combine(Directory.GetCurrentDirectory(), environment.WebRootPath, "Images", fileName);
                using (var fileStream = new FileStream(file_path, FileMode.Create))
                {
                    await brand.ImageFile.CopyToAsync(fileStream);
                }
                brand.ImageName = "Images/" + fileName;
                _context.Add(brand);
                brand.StoreId = id;
                await _context.SaveChangesAsync();
                return RedirectToAction("StoreDetails", "Plots", new { id = id });
            }
            
            return View(brand);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            
            
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int storeid,[Bind("BrandId,BrandName,BrandUrl,ImageName,StoreId,ImageFile")] Brand brand)
        {
            if (id != brand.BrandId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string fileName = Path.GetFileName(brand.ImageFile.FileName);
                    string file_path = Path.Combine(Directory.GetCurrentDirectory(), environment.WebRootPath, "Images", fileName);
                    using (var fileStream = new FileStream(file_path, FileMode.Create))
                    {
                        await brand.ImageFile.CopyToAsync(fileStream);
                    }
                    brand.ImageName = "Images/" + fileName;
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("StoreDetails", "Plots", new { id = storeid });
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId", brand.StoreId);
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                
                .Include(b => b.Store)
                .FirstOrDefaultAsync(m => m.BrandId == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int storeid)
        {
            var brand = await _context.Brands.FindAsync(id);
            var product= await _context.Products.Where(p=>p.BrandId==id).ToListAsync();
            brand.Products.Clear();
            _context.Brands.Remove(brand);
            foreach (var item in product) {
            _context.Products.Remove(item);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("StoreDetails", "Plots", new { id = storeid });
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.BrandId == id);
        }
    }
}

ABCD-OnlineMall/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ABCD_OnlineMall.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace ABCD_OnlineMall.Controllers
{
    public class ProductsController : Controller
    {
        private readonly mallDBContext _context;
        private readonly IWebHostEnvironment environment;

        public ProductsController(mallDBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            environment = hostEnvironment;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchString)
        {
            var mallDBContext = from m in _context.Products.Include(p => p.Brand).Include(p => p.Store) select m;
            if (!String.IsNullOrEmpty(searchString)) { 
                mallDBContext = mallDBContext.Where(s=>s.Category.Contains(searchString));
            }
            
            return View(await mallDBContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Store)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
        public async Task<IActionResult> DetailsClient(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Store)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName");
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "StoreId");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("ProductId,ProductName,StoreId,BrandId,Category,ImageName,ImageFile")] Product product)
        {
            if (ModelState.IsValid)
            {
                
                string fileName = Path.GetFileName(product.ImageFile.FileName);
                string file_path = Path.Combine(Directory.GetCurrentDirectory(), environment.WebRootPath, "Images", fileName);
                using (var fileStream = new FileStream(file_path, FileMode.Create))
                {
                    await product.ImageFile.CopyToAsync(fileStream);
                }
                product.ImageName = "Images/" + fileName;
                _context.Add(product);
                product.StoreId = id;
                await _context.SaveChangesAsync();
                return RedirectToAction("StoreDetails", "Plots", new { id = id });
            }
            
            ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName", product.BrandId);

            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName", product.BrandId);

            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,int storeid, [Bind("ProductId,ProductName,StoreId,BrandId,Category,ImageName,ImageFile")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string fileName = Path.GetFileName(product.ImageFile.FileName);
                    string file_path = Path.Combine(Directory.GetCurrentDirectory(), environment.WebRootPath, "Images", fileName);
                    using (var fileStream = new FileStream(file_path, FileMode.Create))
                    {
                        await product.ImageFile.CopyToAsync(fileStream);
                    }
                    product.ImageName = "Images/" + fileName;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("StoreDetails", "Plots", new { id = storeid });
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "BrandId", "BrandName", product.BrandId);

            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Store)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int storeid)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction("StoreDetails", "Plots", new { id = storeid });

        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

ABCD-OnlineMall/Views/Products/Create.cshtml
@model ABCD_OnlineMall.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminIndex.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create Product</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Create</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="Create" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label asp-for="ProductName"></label>
                                    <input asp-for="ProductName" class="form-control" placeholder="Enter product name" required>
                                    <span asp-validation-for="ProductName" class="text-danger"></span>

                                </div>
                                <div class="form-group">
                                    <label asp-for="BrandId" class="control-label"></label>
                                    <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandId" required></select>
                                    <span asp-validation-for="BrandId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    @{
                                        List<SelectListItem> listItems = new List<SelectListItem>();
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Clothing",
                                            Value = "Clothing",
                                            Selected = true
                                        });
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Food",
                                            Value = "Food"

                                        });
                                        listItems.Add(new SelectListItem
                                        {
                                            Text = "Other",
                                            Value = "Other"
                                        });
                                    }

                                    @Html.DropDownListFor(model => model.Category, listItems, "-- Select Status --")
                                </div>
                                <div class="form-group">
                                    <label asp-for="ImageName"></label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" asp-for="ImageFile" class="custom-file-input" value="" required>
                                            <span asp-validation-for="ImageName" class="text-danger"></span>
                                            <label class="custom-file-label" asp-for="ImageName"></label>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

ABCD-OnlineMall/Views/Products/Delete.cshtml
@model ABCD_OnlineMall.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content("~/"+Model.ImageName)" width="180" height="200" alt="Images" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandId)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ABCD-OnlineMall/Views/Products/DetailsClient.cshtml
@model ABCD_OnlineMall.Models.Product

@{
    ViewData["Title"] = "DetailsClient";
}
@section onload{ 
    <script src="~/client/js/onload.js"></script>
}
@section productdetailcss{ 
    <link href="~/client/css/productdetail.css" rel="stylesheet" />
}
<div class="product-detail-1200">
    <div class="card-container">
        <div class="card u-clearfix">
            <div class="card-body">
                <span class="card-number card-circle subtle">SG</span>
                <span class="card-author subtle">
                    @Html.DisplayFor(model => model.Category)
                </span>
                <h2 class="card-title">
                    @Html.DisplayFor(model => model.ProductName)
                </h2>
                <span class="card-description subtle">
                   Store: <a asp-controller="Plots" asp-action="StoreDetailsClient" asp-route-id="@Model.Store.StoreId">@Html.DisplayFor(model => model.Store.StoreName)</a>
                </span>
                <br />
                <span class="card-description subtle">
                   Brand: <a asp-controller="Brands" asp-action="DetailsClient" asp-route-id="@Model.Brand.BrandId">@Html.DisplayFor(model => model.Brand.BrandName)</a>
                </span>
                <div class="card-read">Read</div>
                <span class="card-tag card-circle subtle">C</span>
            </div>
            <img src="@Url.Content("~/"+Model.ImageName)" alt="" class="card-media" />
        </div>
        <div class="card-shadow"></div>
    </div>
</div>


@*<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content("~/"+Model.ImageName)" width="180" height="200" alt="Images" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Brands" asp-action="Details" asp-route-id="@Model.BrandId"><img src="@Url.Content("~/"+Model.Brand.ImageName)" width="180" height="200" alt="Images" /></a>

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Store)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Store.StoreId)
        </dd>
    </dl>
</div>*@

ABCD-OnlineMall/Views/Products/Index.cshtml
@model IEnumerable<ABCD_OnlineMall.Models.Product>

@{
    ViewData["Title"] = "Index";
}
@section onload{
    <script src="~/client/js/onload.js"></script>
}
@section productcss{
    <link href="~/client/css/product.css" rel="stylesheet" />
}
<div class="band-wrap">
    <div class="headingAll">
        <h1 class="heading-main">Products</h1>
    </div>
    <form asp-controller="Products" asp-action="Index">
        <div class="form-group-wrap">
            <div class="form-group">
                <select class="form-control" id="sel1" name="searchString">
                    <option>Select category</option>
                    <option>Clothing</option>
                    <option>Food</option>
                    <option>Other</option>
                </select>
            </div>
            <input type="submit" value="Filter" class="form-submit" />
        </div>
    </form>

    <div class="band">
        @foreach (var item in Model)
        {
            <div class="item">
                <a asp-controller="Products" asp-action="DetailsClient" asp-route-id="@item.ProductId"
                   class="card">
                    <div class="thumb"
                         style="background-image: url(/@item.ImageName);">
                    </div>
                    <article>
                        <h1>
                            @Html.DisplayFor(modelItem => item.ProductName)
                        </h1>
                        <span>
                            @Html.DisplayFor(modelItem => item.Category)
                        </span>
                    </article>
                </a>
            </div>
        }
    </div>
 </div>
    <script>
        document.getElementsByClassName('item')[0].classList.add('item-1');
    </script>


    @*<p>
        <a asp-action="Create">Create New</a>
    </p>
    <form asp-controller="Products" asp-action="Index">
        <p>

            <div class="form-group">
                <label for="sel1">Category:</label>
                <select class="form-control" id="sel1" name="searchString">
                    <option></option>
                    <option>Clothing</option>
                    <option>Food</option>
                    <option>Other</option>

                </select>
            </div>
            <input type="submit" value="Filter" />
        </p>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Brand)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Store)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                    <a asp-controller="Products" asp-action="DetailsClient" asp-route-id="@item.ProductId">
                        <img src="~/@item.ImageName" width="120" height="80" alt="Images" />
                    </a>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand.BrandId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Store.StoreId)
                    </td>

                </tr>
            }
        </tbody>
    </table>*@