ABCD-OnlineMall/Controllers/CinemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ABCD_OnlineMall.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace ABCD_OnlineMall.Controllers
{
    public class CinemasController : Controller
    {
        private readonly mallDBContext _context;
        private readonly IWebHostEnvironment environment;
        public CinemasController(mallDBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            environment = hostEnvironment;
        }

        // GET: Cinemas
        public async Task<IActionResult> Index()
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            var mallDBContext = _context.Cinemas.Include(c => c.Movie);
            return View(await mallDBContext.ToListAsync());
        }
        public async Task<IActionResult> IndexSeatReserve()
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            var mallDBContext = _context.Seatreserves;
            return View(await mallDBContext.ToListAsync());
        }

        public IActionResult IndexChart()
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            var cinem1 = _context.Cinemas.Where(m => m.CinemaId == 1).FirstOrDefault();
            var cinem2 = _context.Cinemas.Where(m => m.CinemaId == 2).FirstOrDefault();
            var cinem3 = _context.Cinemas.Where(m => m.CinemaId == 3).FirstOrDefault();
            var cinem4 = _context.Cinemas.Where(m => m.CinemaId == 4).FirstOrDefault();
            var cinem5 = _context.Cinemas.Where(m => m.CinemaId == 5).FirstOrDefault();
            var cinem6 = _context.Cinemas.Where(m => m.CinemaId == 6).FirstOrDefault();
            var movie1 = _context.Movies.Where(m => m.CinemaId == 1).FirstOrDefault();
            var movie2 = _context.Movies.Where(m => m.CinemaId == 2).FirstOrDefault();
            var movie3 = _context.Movies.Where(m => m.CinemaId == 3).FirstOrDefault();
            var movie4 = _context.Movies.Where(m => m.CinemaId == 4).FirstOrDefault();
            var movie5 = _context.Movies.Where(m => m.CinemaId == 5).FirstOrDefault();
            var movie6 = _context.Movies.Where(m => m.CinemaId == 6).FirstOrDefault();
            var sales1 = _context.Seatreserves.Count(s => s.CinemaId == 1);
            var sales2 = _context.Seatreserves.Count(s => s.CinemaId == 2);
            var sales3 = _context.Seatreserves.Count(s => s.CinemaId == 3);
            var sales4 = _context.Seatreserves.Count(s => s.CinemaId == 4);
            var sales5 = _context.Seatreserves.Count(s => s.CinemaId == 5);
            var sales6 = _context.Seatreserves.Count(s => s.CinemaId == 6);

            if (cinem1.MovieId != null)
            {
                ViewBag.movie1 = movie1.Title;
                ViewBag.sales1 = sales1 * movie1.Price;
            }
            else
            {
                ViewBag.movie1 = "Empty";
                ViewBag.sales1 = 0;
            }
            if (cinem2.MovieId != null)
            {
                ViewBag.movie2 = movie2.Title;
                ViewBag.sales2 = sales2 * movie2.Price;
            }
            else
            {
                ViewBag.movie2 = "Empty";
                ViewBag.sales2 = 0;
            }
            if (cinem3.MovieId != null)
            {
                ViewBag.movie3 = movie3.Title;
                ViewBag.sales3 = sales3 * movie3.Price;
            }
            else
            {
                ViewBag.movie3 = "Empty";
                ViewBag.sales3 = 0;
            }
            if (cinem4.MovieId != null)
            {
                ViewBag.movie4 = movie4.Title;
                ViewBag.sales4 = sales4 * movie4.Price;
            }
            else
            {
                ViewBag.movie4 = "Empty";
                ViewBag.sales4 = 0;
            }
            if (cinem5.MovieId != null)
            {
                ViewBag.movie5 = movie5.Title;
                ViewBag.sales5 = sales5 * movie5.Price;
            }
            else
            {
                ViewBag.movie5 = "Empty";
                ViewBag.sales5 = 0;
            }
            if (cinem6.MovieId != null)
            {
                ViewBag.movie6 = movie6.Title;
                ViewBag.sales6 = sales6 * movie6.Price;
            }
            else
            {
                ViewBag.movie6 = "Empty";
                ViewBag.sales6 = 0;
            }
            //ViewBag.sales2 = sales2 * movie2.Price;
            //ViewBag.sales3 = sales3 * movie3.Price;
            //ViewBag.sales4 = sales4 * movie4.Price;
            //ViewBag.sales5 = sales5 * movie5.Price;
            //ViewBag.sales6 = sales6 * movie6.Price;
            //ViewBag.movie1 = movie1.Title;
            //ViewBag.movie2 = movie2.Title;
            //ViewBag.movie3 = movie3.Title;
            //ViewBag.movie4 = movie4.Title;
            //ViewBag.movie5 = movie5.Title;
            //ViewBag.movie6 = movie6.Title;
            return View();
        }
        public async Task<IActionResult> IndexClient()
        {
            var mallDBContext = _context.Movies;
            return View(await mallDBContext.ToListAsync());
        }
        public async Task<IActionResult> PickSeat(TimeSpan time, int cinema, DateTime date, int price, string title)
        {


            var model = new viewmodel1();
            model.Seat = await _context.Seats.ToListAsync();
            model.Seatre2 = await _context.Seatreserves.Where(s => s.CinemaId == cinema && s.Showtime == time && s.SeatreserveDate == date).ToListAsync();
            int code;
            do
            {
                Random generator = new Random();
                String r = generator.Next(0, 100000).ToString("D5");
                code = int.Parse(r.ToString());

            } while (_context.Seatreserves.Any(c => c.SeatreserveCode == code));
            ViewBag.time = time;
            ViewBag.cinema = cinema;
            ViewBag.date = date;
            ViewBag.price = price;
            ViewBag.code = code;
            ViewBag.title = title;

            return View(model);
        }
        public IActionResult CreateReserve(TimeSpan time, int cinema, DateTime date, int price, int code, int total, string title)
        {

            int cinema2 = int.Parse(cinema.ToString());
            var model = new viewmodel1();
            model.Seat = _context.Seats.ToList();
            model.Seatre2 = _context.Seatreserves.Where(s => s.CinemaId == cinema2 && s.Showtime == time && s.SeatreserveDate == date).ToList();
            ViewBag.time = time;
            ViewBag.cinema = cinema2;
            ViewBag.date = date;
            ViewBag.price = price;
            ViewBag.code = code;
            ViewBag.total = total;
            ViewBag.title = title;
            return View(model);
        }

        // POST: Seatres/CreateSeat

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateReserve(int[] seat, TimeSpan time, int cinema, DateTime date, string name, int price, int code, int total, string title, Seatreserve seatreserve)
        {
            foreach (int? s in seat)
            {
                var newSeatre = new Seatreserve();
                newSeatre.CinemaId = cinema;
                newSeatre.SeatreserveDate = date;
                newSeatre.Showtime = time;
                newSeatre.SeatId = s;
                newSeatre.SeatreserveCode = code;
                newSeatre.SeatreserveName = name;

                _context.Add(newSeatre);
                await _context.SaveChangesAsync();
            }
            TempData["movietitle"] = title;
            TempData["movietitle"] = title;
            TempData["time"] = time.ToString();
            TempData["cinema"] = cinema.ToString();
            TempData["date"] = date.Date.ToString("dd. MM. yyyy");
            TempData["seat"] = seat;
            TempData["name"] = name.ToString();
            TempData["total"] = price * seat.Length;
            TempData["code"] = code;
            return RedirectToAction(nameof(Ticket));

        }
        public IActionResult Ticket()
        {
            ViewBag.movietitle = TempData["movietitle"];
            ViewBag.time = TempData["time"];
            ViewBag.cinema = TempData["cinema"];
            ViewBag.date = TempData["date"];
            ViewBag.seat = TempData["seat"];
            ViewBag.name = TempData["name"];
            ViewBag.total = TempData["total"];
            ViewBag.code = TempData["code"];
            return View();
        }
        // GET: Cinemas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Cinemas)
                .FirstOrDefaultAsync(c => c.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }
        public async Task<IActionResult> MovieDetailsAdmin(int? id)
        {
            string json = HttpContext.Session.GetString("name");
            if (json == null)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return NotFound();
            }

ABCD-OnlineMall/Controllers/HomeController.cs
using ABCD_OnlineMall.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ABCD_OnlineMall.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ABCD-OnlineMall/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ABCD_OnlineMall.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace ABCD_OnlineMall.Controllers
{
    public class StoresController : Controller
    {
        private readonly mallDBContext _context;
        private readonly IWebHostEnvironment environment;

        public StoresController(mallDBContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            environment = hostEnvironment;
        }

        // GET: Stores
        public async Task<IActionResult> Index(string searchString)
        {
            
            var mallDBContext =from m in _context.Stores.Include(s => s.Plot) select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                mallDBContext = mallDBContext.Where(s => s.StoreName.Contains(searchString));
            }
            return View(await mallDBContext.ToListAsync());
        }
        public async Task<IActionResult> IndexFood()
        {

            var mallDBContext =  _context.Stores.Include(s => s.Plot).Where(s=>s.StoreCategory.Equals("Food"));
            
            return View(await mallDBContext.ToListAsync());
        }
        public async Task<IActionResult> IndexClothing()
        {

            var mallDBContext = _context.Stores.Include(s => s.Plot).Where(s => s.StoreCategory.Equals("Clothing"));

            return View(await mallDBContext.ToListAsync());
        }
        public async Task<IActionResult> IndexOther()
        {

            var mallDBContext = _context.Stores.Include(s => s.Plot).Where(s => s.StoreCategory.Equals("Other"));

            return View(await mallDBContext.ToListAsync());
        }


        // GET: Stores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.FindAsync(id);
            if (store == null)
            {
                return NotFound();
            }
            ViewData["PlotId"] = new SelectList(_context.Plots, "PlotId", "PlotId", store.PlotId);
            return View(store);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StoreId,StoreName,OpenTime,CloseTime,StoreAbout,ImageName,PromoImageName,StoreDescription,StoreCategory,PlotId,ImageFile,ImagePromo")] Store store)
        {
            if (id != store.StoreId)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction("IndexAdmin", "Plots");
            }

            if (store.ImageFile != null)
            {
                string fileName = Path.GetFileName(store.ImageFile.FileName);
                string file_path = Path.Combine(Directory.GetCurrentDirectory(), environment.WebRootPath, "Images", fileName);
                using (var fileStream = new FileStream(file_path, FileMode.Create))
                {
                    await store.ImageFile.CopyToAsync(fileStream);
                }
                store.ImageName = "Images/" + fileName;
            }

            
            if (store.ImagePromo != null)
            {
                string fileName2 = Path.GetFileName(store.ImagePromo.FileName);
                string file_path2 = Path.Combine(Directory.GetCurrentDirectory(), environment.WebRootPath, "Images", fileName2);
                using (var fileStream2 = new FileStream(file_path2, FileMode.Create))
                {
                    await store.ImagePromo.CopyToAsync(fileStream2);
                }
                store.PromoImageName = "Images/" + fileName2;
            }
            _context.Attach(store).State = EntityState.Modified;


            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!StoreExists(store.StoreId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("IndexAdmin","Plots");
            ViewData["PlotId"] = new SelectList(_context.Plots, "PlotId", "PlotId", store.PlotId);
            return View(store);
        }



        private bool StoreExists(int id)
        {
            return _context.Stores.Any(e => e.StoreId == id);
        }
       
    }
}

ABCD-OnlineMall/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Main.cshtml";
}
@section homejs{
    <script src="~/client/js/home.js"></script>
}
@section homecss{
    <link href="~/client/css/home.css" rel="stylesheet" />
}

<section class="back-ground-img" style="background-image: url(../../../client/img/backround-1.jpg)">
    <div class="blur">
        <div class="slogan-in-backround">
            <span class="slogan-in-backround__slogan">Transforming shopping into an experience.</span>
            <span class="slogan-in-backround__text">ABCD Mall. Where you have it all!</span>
        </div>
        <div class="time">
            <div class="time-item">
                <div class="time-item-child">
                    <span class="time-item-child-number"></span>
                    <span class="time-item-child-text">DAYS</span>
                </div>
            </div>
            <div class="time-item">
                <div class="time-item-child">
                    <span class="time-item-child-number"></span>
                    <span class="time-item-child-text">HOURS</span>
                </div>
            </div>
            <div class="time-item">
                <div class="time-item-child">
                    <span class="time-item-child-number"></span>
                    <span class="time-item-child-text">MINUTES</span>
                </div>
            </div>
            <div class="time-item">
                <div class="time-item-child">
                    <span class="time-item-child-number"></span>
                    <span class="time-item-child-text">SECONDS</span>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Introduce / Time open -->
<div class="home">
    <div class="home-wrapper">
        <div class="grid">
            <div class="col-4">
                <div class="item-icon">
                    <i class="fas fa-info" ></i>
                </div>
                <a href="/Contact/Index" class="heading-link">Introduce</a>
                <p class="text">Thank you for Comming !</p>
            </div>
            <div class="col-4">
                <div class="item-icon">
                    <i class="fas fa-location-arrow"></i>
                </div>
                <h1 class="heading">Location</h1>
                <p class="text">
                    590 Cach Mang Thang 8, District 3, Ho Chi Minh City
                </p>
            </div>
            <div class="col-4">
                <div class="item-icon">
                    <i class="far fa-clock"></i>
                </div>
                <h1 class="heading">Time Open</h1>
                <p class="text">
                    T2 - T6: 11h00 - 21h00 | T7,CN: 10h00 - 21h00
                </p>
            </div>
        </div>
    </div>
</div>
<!-- End Introduce -->
<!-- Tendecy -->
<div class="home-tendency">
    <h1 class="tendency-heading">
        <span class="tendency-heading__border">Tendency</span>
    </h1>
    <div class="grid-tendency">
        <a class="col-tendency-4" asp-action="IndexFood" asp-controller="Stores">
            <div class="col-tendency-img"
                 style="background-image: url(../../../client/img/food.jpg)">
                <h2 class="col-tendency-heading">Foods</h2>
            </div>
        </a>
        <a class="col-tendency-4" asp-action="IndexClothing" asp-controller="Stores">
            <div class="col-tendency-img"
                 style="background-image: url(../../../client/img/clothings.jpg)">
                <h2 class="col-tendency-heading">Clothings</h2>
            </div>
        </a>

        <a class="col-tendency-4" asp-action="IndexClient" asp-controller="Cinemas" target="_blank">
            <div class="col-tendency-img"
                 style="background-image: url(../../../client/img/movies.jpg)">
                <h2 class="col-tendency-heading">Movies</h2>
            </div>
        </a>
        <a class="col-tendency-4" asp-action="IndexOther" asp-controller="Stores">
            <div class="col-tendency-img"
                 style="background-image: url(../../../client/img/other.jpg)">
                <h2 class="col-tendency-heading">Other</h2>
            </div>
        </a>
    </div>
</div>

<!-- End Tendecy -->